### ISSUE TITLE
快捷命令 “唯一进程” 选项设置调用出错，能否帮忙看看？

### ISSUE THREAD

**Issue by patchor** [chenall/ALMRun#11]
因为经常调用远程桌面，同时有时会不经意间重复调用。所以刚才尝试了一下在调用远程桌面是，设置了 唯一进程。

但是在设置唯一进程后，重复调用的时候，会弹出一个空白块！ 此空白块只能在关闭第一次启动的远程桌面后才消失！
同时，在关闭远程调用后，再次调用远程桌面没有响应。只能取消 唯一进程选项才能执行

chenall 能否帮忙看看？

**Comment by chenall** [comment]
新的问题在 #19
