### ISSUE TITLE
V72 desc.ico 编译错误请教

### ISSUE THREAD

**Issue by patchor** [chenall/ALMRun#17]
下载了V72 的源码

已经安装VS 2012 、wxWidgets-3.0.0 和 cmake-3.1.0-win32-x86。

编译 D:\dev\wxWidgets-3.0.1\build\msw\wx_vc11.sln`文件编译 **Release** 和 **Debug** 两个版本

在ALMrun 下cmake .. 成功

在VS2012 中打开 ALMrun.sln  编译时候出错如下：

2>libcmt.lib(invarg.obj) : error LNK2005: __invoke_watson 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(tolower.obj) : error LNK2005: _tolower 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(wsetloca.obj) : error LNK2005: __configthreadlocale 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(wsetloca.obj) : error LNK2005: __create_locale 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(wsetloca.obj) : error LNK2005: __free_locale 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(crtheap.obj) : error LNK2005: __calloc_crt 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(crt0dat.obj) : error LNK2005: __amsg_exit 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(crt0dat.obj) : error LNK2005: __cexit 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(crt0dat.obj) : error LNK2005: __exit 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(crt0dat.obj) : error LNK2005: __initterm_e 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(crt0dat.obj) : error LNK2005: _exit 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(_wctype.obj) : error LNK2005: _iswalnum 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(_wctype.obj) : error LNK2005: _iswalpha 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(_wctype.obj) : error LNK2005: _iswdigit 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(_wctype.obj) : error LNK2005: _iswprint 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(_wctype.obj) : error LNK2005: _iswspace 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(mlock.obj) : error LNK2005: __lock 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(mlock.obj) : error LNK2005: __unlock 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(winapisupp.obj) : error LNK2005: ___crtGetShowWindowMode 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(winapisupp.obj) : error LNK2005: ___crtSetUnhandledExceptionFilter 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(winapisupp.obj) : error LNK2005: ___crtTerminateProcess 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(winapisupp.obj) : error LNK2005: ___crtUnhandledException 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(winxfltr.obj) : error LNK2005: __XcptFilter 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(dosmap.obj) : error LNK2005: __errno 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(hooks.obj) : error LNK2005: "void __cdecl terminate(void)" (?terminate@@YAXXZ) 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(crt0init.obj) : error LNK2005: ___xi_a 已经在 MSVCRT.lib(cinitexe.obj) 中定义
2>libcmt.lib(crt0init.obj) : error LNK2005: ___xi_z 已经在 MSVCRT.lib(cinitexe.obj) 中定义
2>libcmt.lib(crt0init.obj) : error LNK2005: ___xc_a 已经在 MSVCRT.lib(cinitexe.obj) 中定义
2>libcmt.lib(crt0init.obj) : error LNK2005: ___xc_z 已经在 MSVCRT.lib(cinitexe.obj) 中定义
2>libcmt.lib(errmode.obj) : error LNK2005: ___set_app_type 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(fflush.obj) : error LNK2005: _fflush 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(_file.obj) : error LNK2005: ___iob_func 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>libcmt.lib(towlower.obj) : error LNK2005: _towlower 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
2>     正在创建库 D:/dev/ALMRun_1.2.0.72/src/Release/ALMRun.lib 和对象 D:/dev/ALMRun_1.2.0.72/src/Release/ALMRun.exp
2>LINK : warning LNK4098: 默认库“MSVCRT”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
2>MSVCRT.lib(cinitexe.obj) : warning LNK4098: 默认库“libcmt.lib”与其他库的使用冲突；请使用 /NODEFAULTLIB:library
2>D:\dev\ALMRun_1.2.0.72\src\Release\ALMRun.exe : fatal error LNK1169: 找到一个或多个多重定义的符号
3>------ 已跳过生成: 项目: ALL_BUILD, 配置: Release Win32 ------
3>没有为此解决方案配置选中要生成的项目 
========== 生成: 成功 1 个，失败 1 个，最新 0 个，跳过 1 个 ==========

**Comment by chenall** [comment]
抱歉，看了下是我上传的文件不完整，已经更新，直接更新一下就行了

**Comment by chenall** [comment]
error LNK2005: ___crtTerminateProcess 已经在 MSVCRT.lib(MSVCR110.dll) 中定义
在属性页C/C++ 里面"代码生成"=>运行库=>选择 MT开头的(Release使用mt,Debug使用mtd)

可以用文本批量替换工具修改wxWidget的编译设置再重新编译

需要替换的文件wx_vc11_*.vcxproj
MultiThreadedDLL  替换为 MultiThreaded
MultiThreadedDebugDLL 替换为 MultiThreadedDebug

然后重新编译一下wxWidget应该就行了.

**Comment by patchor** [comment]
谢谢，现在已经把环境调通了。

在网上找到了一段代码，检查某个程序名是否已经在系统运行列表中存在。以便通过程序名限制唯一进程不能重复启动。但是对VC++ 的各种类型确实不太了解， checkProg 中的strstr 没法调通

chenall 能否帮忙接下来看看，通过这样方式实现唯一进程调用呢？

BOOL CheckProg(LPCTSTR strSearch)
{
  PROCESSENTRY32   ProInfo;  
  ProInfo.dwSize = sizeof(PROCESSENTRY32); 
  HANDLE  hProSnap=CreateToolhelp32Snapshot(TH32CS_SNAPALL,0);  

  if   (::Process32First(hProSnap,&ProInfo))  
  {  
	  for   (;::Process32Next(hProSnap,&ProInfo);)  
	  {  
		  //判断被调用的程序名，是否已经在运行程序列表中
//		  if (strstr(strSearch,(char*)ProInfo.szExeFile) != NULL)
//		  if (strstr((char*)strSearch,"mstsc.exe") != NULL)
		  {  
//			  MessageBox(NULL, ProInfo.szExeFile,_T("Found Into CheckProg"), MB_OK);
//			  MessageBox(NULL, ProInfo.szExeFile,strSearch, MB_OK);
			  return TRUE;
		  }  
	  }  
  }  

return FALSE;
}

DWORD MerryController::ShellExecute(const wxString& commandName,
	const wxString& commandArg,
	const wxString& workingDir,
	const wxString& show) const
{
	// wxLogNull logNo;


	int showCommand = SW_SHOW;
	bool runas = false;
	bool winexec = false;
	bool NeedGetPath = true;
	bool SavePid = false;

	if (g_config && g_config->get(cmdSingleProecss))
		SavePid = true;

	if (show.IsSameAs(wxT("hide"), false))
		showCommand = SW_HIDE;
	else if (show.IsSameAs(wxT("min"), false))
		showCommand = SW_SHOWMINIMIZED;
	else if (show.IsSameAs(wxT("max"), false))
		showCommand = SW_SHOWMAXIMIZED;
	size_t len = commandName.size();
	size_t n;
	for(n = 0;n<len;++n)
	{
		wxChar c = commandName[n];
		switch(c)
		{
			case '?'://前导'?'唯一进程
				SavePid = true;
				continue;
			case '@'://前导'@'隐藏窗口运行
				showCommand = SW_HIDE;
				continue;
			case '*'://以管理员权限运行
				runas = true;
				continue;
			case '>'://根据系统判断,NT6以上以管理员权限运行.
				if (::wxGetWinVersion() >= wxWinVersion_6)
					runas = true;
				continue;
			case '+'://强制参数标志
				continue;
			case '\2'://强制使用WinExec 函数执行
				winexec = true;
			case '\1'://\1\2 标志说明该命令已经经过处理,不需要再次处理
				NeedGetPath = false;
				continue;
			case '|'://命令标志结尾.
				++n;
				break;
			case ' ':
			case '\t':
				continue;
			default:
				break;
		}
		break;
	}

	wxString cmdName = commandName.substr(n);
	if (cmdrun_flags & CMDRUN_FLAG_RUNAS) runas = true;
	if (cmdrun_flags & CMDRUN_FLAG_HIDE) showCommand = SW_HIDE;
	cmdrun_flags = 0;

	if (!LocationExec)
	{
		__DEBUG_BEGIN(cmdName.c_str());
		SHELLEXECUTEINFO ShExecInfo = {0};
		ShExecInfo.cbSize = sizeof(SHELLEXECUTEINFO);
		ShExecInfo.fMask = SEE_MASK_NOCLOSEPROCESS;
		ShExecInfo.hwnd = NULL;
		ShExecInfo.lpVerb = runas?_T("RunAs"):NULL;
		ShExecInfo.lpFile = cmdName.c_str();    //要运行的文件
		ShExecInfo.lpParameters =commandArg.c_str();
		ShExecInfo.lpDirectory = workingDir.c_str();
		ShExecInfo.nShow = showCommand;
		ShExecInfo.hInstApp = NULL;

			if (SavePid )
			{
				//传入完整调用名称，带路径等
//				MessageBox(NULL,ShExecInfo.lpFile,_T("Search"), MB_OK);
				if (CheckProg(ShExecInfo.lpFile))
				{
//					MessageBox(NULL, ,ShExecInfo.lpFile, MB_OK);
					MessageBox(NULL,ShExecInfo.lpFile,_T("已经在运行"), MB_OK);
				}
				else
				{
					if (::ShellExecuteEx(&ShExecInfo))
					{
						return SavePid?GetProcessId(ShExecInfo.hProcess):1;
					}
				}

			}

		return 0;
	}

	LocationExec = false;//定位文件位置标志复位
	wxString FullcmdName = NeedGetPath?GetCMDPath(cmdName):cmdName;
	if (FullcmdName.empty())
		return 0;

	FullcmdName.Replace('/','\\');

#ifdef _ALMRUN_CONFIG_H_
	if (!g_config->Explorer.empty())
		::WinExec(wxString::Format("%s \"%s\"",g_config->Explorer,FullcmdName),SW_SHOW);
	else
#endif//ifdef _ALMRUN_CONFIG_H_
		::ShellExecute(NULL,NULL,_T("explorer.exe"),_T("/n,/select,")+FullcmdName.c_str(),NULL, SW_SHOW);
	return 0;
}

**Comment by chenall** [comment]
不知任务管理器列出所有运行的任务PID是怎么实现的,我对WINDOWS编程不太熟悉的说,只能勉强能用.

麻烦你有空找找看有没有相关的代码,我觉得用pid来判断是最好的,因为每个进程都有一个唯一的ID,若是简单的用文件名来判断,有可能会有同名的.

**Comment by patchor** [comment]
下面这段代码，就是遍历当前所有运行程序和传入的程序名进行比较以判断是否该程序已经有运行历程，但是我不熟悉该怎样用 strstr 判断文件名是否已经在运行。你可以看看如何修改一下。如果需要PID 。 PROCESSENTRY32 结构中好像也有这个属性，你看看一下

typedef struct tag PROCESSENTRY32
{
    DWORD dwSize;
    DWORD cntUsage;
    DWORD th32ProcessID;
    ULONG_PTR th32DefaultHeapID;
    DWORD th32ModuleID;
    DWORD cntThreads;
    DWORD th32ParentProcessID;
    LONG pcPriClassBase;
    DWORD dwFlags;
    TCHAR szExeFile[MAX_PATH];
} PROCESSENTRY32, *PPROCESSENTRY32;


BOOL CheckProg(LPCTSTR strSearch)
{
PROCESSENTRY32 ProInfo;

ProInfo.dwSize = sizeof(PROCESSENTRY32); 
HANDLE hProSnap=CreateToolhelp32Snapshot(TH32CS_SNAPALL,0);

if (::Process32First(hProSnap,&ProInfo))

{

for (;::Process32Next(hProSnap,&ProInfo);)

{

//判断被调用的程序名，是否已经在运行程序列表中
// if (strstr(strSearch,(char)ProInfo.szExeFile) != NULL)
// if (strstr((char)strSearch,"mstsc.exe") != NULL)
{

// MessageBox(NULL, ProInfo.szExeFile,_T("Found Into CheckProg"), MB_OK);
// MessageBox(NULL, ProInfo.szExeFile,strSearch, MB_OK);
return TRUE;
}

}

}

return FALSE;
}

**Comment by chenall** [comment]
谢谢,我再抽空试试看,如果有PID的话,根据PID就可以dq

**Comment by patchor** [comment]
不客气，期待着好消息




patchor@163.com

发件人： chenall
发送时间： 2015-01-24 17:36
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] V72 desc.ico 编译错误请教 (#17)
谢谢,我再抽空试试看,如果有PID的话,根据PID就可以dq

**Comment by chenall** [comment]
测试了一下,上面的代码是可以获取到进程PID,也能确定唯一进程,但是问题和以前的一样,
就是激活的问题,不能正常激活旧的进程,我网上找了好久没有相到相关代码.

目前的激活还是需要遍历所有窗口,但是这个方法不是很可靠.

**Comment by chenall** [comment]
找到了一个任务管理器的源码,,我研究一下看看.

**Comment by chenall** [comment]
gjq
