### ISSUE TITLE
希望增加功能

### ISSUE THREAD

**Issue by youthcould** [chenall/ALMRun#18]
非常棒的启动工具，Good job
1. Altrun有2个功能（启动时显示窗体，以及执行任务后退出），希望可以加上，这样就可以不用常驻almrun了，可以用hoekey等工具启动
2. 希望支持everything服务
3. 希望支持tab和shift+tab切换选项
4. 希望可能自动删除一部分系统内的服务，由于有些完全用不到，反而让列表比较长

**Comment by youthcould** [comment]
5. 希望如果没有任何搜索到的项目时可以调用Google搜索

多谢

**Comment by youthcould** [comment]
btw，窗口置顶按照如下写出现错误
addCommand{ key = 'A-Q', func = function()
	SetWindowpos(GetForegroundWindow(),-1)
end }
提示attempt to cal global 'SetWindowpos' (a nil value)
不知道是不是我的问题，还请指教，多谢

**Comment by chenall** [comment]
@youthcould 
lua是有区分大小写的,应该是SetWindowPos,调用API请使用文档里面的资料,特别是大小写不能错.

**Comment by chenall** [comment]
再来回前面的问题

1. 启动时显示窗体,这个可以加上,"执行任务后退出"我感觉最好不要,因为每次启动要读一次配置,会比较快,热键管理ALMRUN,可以直接管理热键的.

2. 有支持的呀,输入ev可以看到一般在最后面(可以修改`config\sampleplugins.lua`里面的name="EV",改成其它名称)

3. 这个我就不太明白了,切换什么选项??

4. 你可以自己删除,部份比如config\sample目录里面的lua,你可以打开看一下,不需要的命令可以删除.
    里面都有注释的,还有命令管理器里面也可以删除(默认会自动添加桌面的开始菜单的内容不需要也可以删除)

5 用插件可以实现,把以下内容,另存为Google.lua,放到config目录下就行了,也可以直接添加到`config\sample\plugins.lua`中
```lua
RegisterPlugin('command',{func=function(commandName,...)
    return {name="用Google搜索:"..commandName,desc="ALMRun 运行插件",cmd = "http://www.google.com/search?q="..commandName,order=0}
end})
```

**Comment by youthcould** [comment]
1. 明白
2. 明白了
3. 其实是想的是可以用tab和shift tab来选择匹配项
4. 明白
5. 明白
6. 如果我将部分常用目录（可能是程序，也可能是文档）添加到Almrun自动扫描，来部分代替everything的功能，almrun性能上会有明显变化吗？
7. 多谢你的指教，已经能工作了，但是有个小问题，没有找到api来辅助实现用Alt+G切换窗口的前置或非前置状态，请问有办法实现吗？
addCommand{ name = "windows on top", desc = "windows ontop", key = 'A-G', cmd =  function()
	SetWindowPos(GetForegroundWindow(),-1)
end }

**Comment by chenall** [comment]
3, tab 已经用于输入参数了,选择匹配项直接用数字不是更快?

6. almrun 自动扫描的话会比较慢,因为它主要是用来管理命令的,不是管理文档的.还是配合everything会好一些.

7. 这个肯定是可以实现的,就看对API的应用了.
一个简单例子在(sample\common.lua中)
按Alt+H 来隐藏或显示窗口,第一次隐藏再按显示.

```lua
local curHideWindow
addCommand{ key = 'A-H', cmd = function()
    if not curHideWindow then
        curHideWindow = GetForegroundWindow()
        ShowWindow(curHideWindow, 'hide')
    else
        ShowWindow(curHideWindow, 'normal')
        curHideWindow = nil
    end
end }
```

**Comment by youthcould** [comment]
多谢
