### ISSUE TITLE
远程桌面 唯一进程还是无效

### ISSUE THREAD

**Issue by patchor** [chenall/ALMRun#19]
![image](https://cloud.githubusercontent.com/assets/8335832/5916165/13fd4d4e-a649-11e4-91aa-8fa3594e811c.png)

**Comment by patchor** [comment]
V73 版本，新版本感觉流畅了不少，唯一进程以前的白框也不再出现了

**Comment by patchor** [comment]
但是已经在启动一个远程桌面，并且在运行中
![image](https://cloud.githubusercontent.com/assets/8335832/5916187/5436fd06-a649-11e4-8fd7-c03ee4bec6fd.png)

**Comment by patchor** [comment]
![image](https://cloud.githubusercontent.com/assets/8335832/5916192/6c55d7ae-a649-11e4-84c4-e1ef9f9e506c.png)

**Comment by patchor** [comment]
但是仍然可以调用 mstsc.exe 重新登陆一个新进程。按照设计，应该是在第二次调用时候，如果已经发现有mstsc.exe 程序在运行的实例，应该屏蔽不应再次调用mstsc.exe 了

**Comment by chenall** [comment]
ALMRUN唯一进程的定义是,

 ALMRUN正在运行,并且使用ALMRUN启动的应用,才会有算在唯一进程.

比如你用其它软件或WINDOWS的运行命令启动的一个程序,再用ALMRUN启动这个是不算的.

或者说用ALMRUN启动了一个进程,然后退出ALMRUN重新打开,再次运行该程序也不算是唯一进程.

唯一进程,只记录了对应进程的PID

**Comment by patchor** [comment]
根据传入的带/不带路径的可执行程序名检查是否已经在运行过
BOOL CheckProg(LPCTSTR strSearch)
{

PROCESSENTRY32 ProInfo;
ProInfo.dwSize = sizeof(PROCESSENTRY32); 
HANDLE hProSnap=CreateToolhelp32Snapshot(TH32CS_SNAPALL,0);
//取windows 当前所有已经在执行的程序信息
if (::Process32First(hProSnap,&ProInfo))
{
//已经执行的可执行程序名称，不带路径。如果必要，可以想办法只提取应用程序名称出来
//strSearch 是传入的检查文件名，如  c:\windows\mstsc.exe
//ProInfo.szExeFile 是系统已经在执行的文件名，如 mstsc.exe,用 strstr 来做字符串定位，如果为其中子串，则返回 true
if (strstr(strSearch,(char)ProInfo.szExeFile) != NULL)
return TRUE;
//如果第一个取出的程序非需要检查的程序，则循环提取后续程序进行判断

for (;::Process32Next(hProSnap,&ProInfo);)
{
return TRUE;
}
   }  // end of if
//遍历循环都没有发现当前程序名已经在运行，则返回false
return FALSE;
}

这是typedef struct tag PROCESSENTRY32的结构定义
{
DWORD dwSize;
DWORD cntUsage;
DWORD th32ProcessID;
ULONG_PTR th32DefaultHeapID;
DWORD th32ModuleID;
DWORD cntThreads;
DWORD th32ParentProcessID;
LONG pcPriClassBase;
DWORD dwFlags;
TCHAR szExeFile[MAX_PATH];
} PROCESSENTRY32, *PPROCESSENTRY32; 

然后在调用命令部分修改一下,这样就避免了前述用其它软件或WINDOWS的运行命令启动的一个程序,再用ALMRUN启动或者说用ALMRUN启动了一个进程,然后退出ALMRUN重新打开,再次运行等情况的bug 
(实际现在这几种情况都不是发生的原因)，也会更可靠一点。不知可否？
   if (SavePid )
        {
            if (CheckProg(ShExecInfo.lpFile )) 
           {
                        MessageBox(NULL,ShExecInfo.lpFile,_T("已经在运行,且设置唯一进程"), MB_OK);           
           }
      }
else{if (::ShellExecuteEx(&ShExecInfo)){return SavePid?GetProcessId(ShExecInfo.hProcess):1;}

patchor@163.com

发件人： chenall
发送时间： 2015-01-27 18:04
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] 远程桌面 唯一进程还是无效 (#19)
ALMRUN唯一进程的定义是,
ALMRUN正在运行,并且使用ALMRUN启动的应用,才会有算在唯一进程.
比如你用其它软件或WINDOWS的运行命令启动的一个程序,再用ALMRUN启动这个是不算的.
或者说用ALMRUN启动了一个进程,然后退出ALMRUN重新打开,再次运行该程序也不算是唯一进程.
唯一进程,只记录了对应进程的PID

**Comment by patchor** [comment]
另外，V73 版本，还去掉了 system 等路径的搜索吗？

怎么现在 shutdown 、reboot 现在没有能顾选择出来了呢？

**Comment by chenall** [comment]
如果唯一进程启用,然后启动了该程序,再次启动时没有任何提示,直接重新开了一个程序,那才算是BUG

唯一进程,我测试了没有发现问题,除非你的进程不是ALMRUN管理的,否则不应该失败的,
执行一次之后软件会记录进程PID的,下次运行碰到有PID才会检测唯一进程,顶多就是激活失败(这个也会有提示的),

不打算使用程序名来判断,这样很影响效率(每次启动程序都要判断,这个很浪费时间),并且会造成启动缓慢的效果,就是启动了这个程序,还得等个几秒才会启动(这个看电脑性能),

**Comment by chenall** [comment]
>另外，V73 版本，还去掉了 system 等路径的搜索吗？
>怎么现在 shutdown 、reboot 现在没有能顾选择出来了呢？

这些本来就不搜索的呀,之前的版本有,那是因为有一个ShortCutList.txt在almrun目录下.新的版本已经去掉了这个文件.

**Comment by patchor** [comment]
哈哈，把shortcutlist.txt 加进去了，那个还是挺方便的

**Comment by patchor** [comment]
chenall, 能否帮忙看看一下 CheckProg(LPCTSTR strSearch) 的代码呢

这样的判断方式，或许可以达到我想要的效果

**Comment by chenall** [comment]
如果根据文件名的话上面的代码是可以的,不过若是根据文件的话还需要考虑同名的问题

**Comment by patchor** [comment]
我觉得可以不用考虑同名的问题，毕竟这种情况不多！我觉得只要能够根据文件名来判断，应该足够满足使用要求了




patchor@163.com

发件人： chenall
发送时间： 2015-01-29 11:14
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] 远程桌面 唯一进程还是无效 (#19)
如果根据文件名的话上面的代码是可以的,不过若是根据文件的话还需要考虑同名的问题

**Comment by patchor** [comment]
我用 autohotkey 已经解决唯一进程问题

结贴了
