### ISSUE TITLE
很奇怪的一个现象: 参数选择框不支持模糊查询了

### ISSUE THREAD

**Issue by patchor** [chenall/ALMRun#20]
![image](https://cloud.githubusercontent.com/assets/8335832/5932880/efe28502-a6f0-11e4-9ead-53749e11f1ca.png)

**Comment by patchor** [comment]
V73 的参数选择界面，我现在输入 bet 不能自动选出 bbs.pcbeta.com 了

只能输入从头bbs.pc... 才行

参数筛选算法调整过了吗？

另：还请请教一下，vs2012 里面，almrun 中能否调出mfc 的设计窗口呢？ 有时直接看代码，不好找到对应的入口。对VC++ 真心不懂

**Comment by chenall** [comment]
这个界面是使用wxWidget组件的,没有图形界面的设计窗口...

看了一下,确实是有问题,我再看下,也许是某一个版本改了,忘记了.

**Comment by patchor** [comment]
V68 的模糊查询可用，你可以看看一下V68 的代码

**Comment by chenall** [comment]
看了下好像是因为这个的原因 #9 
回头再看看能不能改一下.

**Comment by chenall** [comment]
汗记性不好, #8 的时候是有支持的,其实是因为我升级了wxWidget,而没有对应修改的原因.

**Comment by chenall** [comment]
重新编译了一下wxWidget,更新上传了,你可以试下看看是否正常

http://pan.baidu.com/s/1mgn7aBY

**Comment by patchor** [comment]
哈哈，不着急。开发本来不容易。且行且珍惜。

我现在看看下载看看




patchor@163.com

发件人： chenall
发送时间： 2015-02-07 11:36
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] 很奇怪的一个现象: 参数选择框不支持模糊查询了 (#20)
重新编译了一下wxWidget,更新上传了,你可以试下看看是否正常
http://pan.baidu.com/s/1mgn7aBY

**Comment by patchor** [comment]
新版本的参数模糊匹配已经可以正常使用了，感觉这个版本的很流畅

远程桌面的唯一进程好像还不行，能否帮忙看看呢？




patchor@163.com

发件人： chenall
发送时间： 2015-02-07 11:36
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] 很奇怪的一个现象: 参数选择框不支持模糊查询了 (#20)
重新编译了一下wxWidget,更新上传了,你可以试下看看是否正常
http://pan.baidu.com/s/1mgn7aBY

**Comment by chenall** [comment]
你是什么系统的呀,我测试了很正常呀.

另外唯一进程不行的话新版应该会有提示的吧?

**Comment by patchor** [comment]
我的操作系统是 windows server 2008R2 。把远程桌面设置成唯一进程，不会像以前那样出来白框什么了，但是也没有直接激活、最大化原有的进程，而是直接运行一个新进程了




patchor@163.com

发件人： chenall
发送时间： 2015-02-09 15:52
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] 很奇怪的一个现象: 参数选择框不支持模糊查询了 (#20)
你是什么系统的呀,我测试了很正常呀.
另外唯一进程不行的话新版应该会有提示的吧?

**Comment by patchor** [comment]
我用 autohotkey 已经解决唯一进程问题

结贴了
