### ISSUE TITLE
命令太长会退出

### ISSUE THREAD

**Issue by zdspxsjl** [chenall/ALMRun#21]
运行这个命令直接报错退出
删短一点就可以运行

[cmds/1]
cmd=C:\Program Files\Chromium\chrome.exe --ppapi-flash-path=c:\WINDOWS\system32\Macromed\Flash\pepflashplayer32_16_0_0_296.dll --ppapi-flash-version=16.0.0.296 --no-first-run --allow-running-insecure-content --user-data-dir=".\data" --disk-cache-dir="%userprofile%\ccache"
key=Alt+C

**Comment by chenall** [comment]
谢谢报告,确实有问题,我查一下原因.

**Comment by chenall** [comment]
已修正,请测试一下

http://pan.baidu.com/s/1kT5jM5p

**Comment by zdspxsjl** [comment]
没问题了,多谢。
