### ISSUE TITLE
很奇怪的一个现象，筛选框选项编辑之后筛选输入项失效了

### ISSUE THREAD

**Issue by patchor** [chenall/ALMRun#23]
最新版的V0.73 流畅、稳定了许多

筛选项也挺方便的。但是今天突然发现一个情况。就是在命令管理项中输入筛选内容、回车后可以正确显示被筛选的命令行设置

**Comment by patchor** [comment]
![image](https://cloud.githubusercontent.com/assets/8335832/6129308/73adcbe4-b178-11e4-9e51-97abb1517efb.png)

**Comment by patchor** [comment]
如果选择一个命令行编辑、确认之后
![image](https://cloud.githubusercontent.com/assets/8335832/6129328/a0ed7d70-b178-11e4-873d-9e7da0bc722d.png)

**Comment by patchor** [comment]
命令行管理中的筛选项突然失效了，就算把光标放在筛选内容中回车，也不能正确显示出符合条件的命令行

![image](https://cloud.githubusercontent.com/assets/8335832/6129349/ceeb301e-b178-11e4-8df0-8d61f4d79214.png)

**Comment by patchor** [comment]
chenall 能否帮忙看看是怎么回事呢？

**Comment by chenall** [comment]
试了下一切正常呀,有没有什么办法可以重现?

**Comment by patchor** [comment]
这是我用 windows psr.exe 操作的一个拷屏，你看看附件是否可以正常下载查看呢？



patchor@163.com

发件人： chenall
发送时间： 2015-02-11 11:22
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] 很奇怪的一个现象，筛选框选项编辑之后筛选输入项失效了 (#23)
试了下一切正常呀,有没有什么办法可以重现?

**Comment by patchor** [comment]
这里有没有办法贴附件呢？ 我从foxmail 直接回复，好像附件没有上传成功

**Comment by patchor** [comment]
或者，能否给一个可以带附件的邮箱，我发给你呢？

**Comment by chenall** [comment]
直接上传到网络上提供下载地址就行了..

**Comment by patchor** [comment]
上传到百度网盘了，你看看一下 

http://pan.baidu.com/s/1bneweMb 




patchor@163.com

发件人： chenall
发送时间： 2015-02-11 11:22
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] 很奇怪的一个现象，筛选框选项编辑之后筛选输入项失效了 (#23)
试了下一切正常呀,有没有什么办法可以重现?

**Comment by chenall** [comment]
OK,明白了,应该算是BUG,不过影响不是很大删除一下原来的搜索就行了,
下个版本修正.

**Comment by patchor** [comment]
OK ， 谢谢chenall !

**Comment by patchor** [comment]
版本号：

![image](https://cloud.githubusercontent.com/assets/8335832/6453854/a931e3ee-c17d-11e4-8057-3a3c14ed7183.png)

筛选框选项编辑之后筛选输入项失效情况还是存在，能否帮忙修正一下？

**Comment by chenall** [comment]
这个应该不会吧,我测试是正常的.

**Comment by patchor** [comment]
在用的这个版本仍然存在这个问题，能否帮忙发一个最新的版本呢？

**Comment by chenall** [comment]
和我这里的版本是一样的,能不能重新录制一个问题的步骤呢?我这里测试是正常的,也许是有其它原因存在.

**Comment by patchor** [comment]
我录制了问题步骤，麻烦看看一下呢

链接: http://pan.baidu.com/s/1nt1cOit 密码: 3z6m

**Comment by chenall** [comment]
http://pan.baidu.com/s/1jGGH4EE
好像你的还是旧版本的试试上面链接的最新版本加NEW那个

**Comment by patchor** [comment]
new 的这个版本还是不行。很奇怪，难道跟我的操作系统类型有关？

另外，new 的这个版本，我把parameters 参数文件也拷过来以后，反倒参数输入不能筛选出对应的参数。所以我回退到原来的版本了

**Comment by chenall** [comment]
可以的话你把整个目录打包发给我测试下.

**Comment by patchor** [comment]
下载带New 的那个版本，筛选框、参数框运行有点异常。我把整个目录打包上传到云盘了，你看看一下

链接: http://pan.baidu.com/s/1GswZO 密码: sojz

**Comment by patchor** [comment]
Chenall，是否我所用版本有问题呢？

**Comment by chenall** [comment]
我重新再传了一下最新的版本(我后面NEW的版本也传错了.)

http://pan.baidu.com/s/1jGGH4EE#path=%252FALMRun

**Comment by patchor** [comment]
谢谢chenall，已经下载最新 73 版本，筛选狂和参数筛选正常。我继续看看一下

**Comment by patchor** [comment]
谢谢chenall，最新版本很稳定。已经解决筛选框和参数选择框问题。

这个issue 可以结掉了
