### ISSUE TITLE
参数窗口偶尔还是有丢失焦点的情况，尤其在输入比较快的情况下。有没有办法彻底解决呢？

### ISSUE THREAD

**Issue by patchor** [chenall/ALMRun#24]
参数窗口偶尔还是有丢失焦点的情况，尤其在命令窗口输入按键速度比较快的时候。almrun 已经成为使用频率最高的一个软件，有没有办法彻底解决呢？

**Comment by patchor** [comment]
![image](https://cloud.githubusercontent.com/assets/8335832/6185155/10721d34-b3a6-11e4-8693-f8bae8fa3fa1.png)

**Comment by chenall** [comment]
我再看看有没有什么好一点儿的办法.

**Comment by patchor** [comment]
chenall，期待着好消息！

**Comment by chenall** [comment]
先试试之个,看看能不能解决.
http://pan.baidu.com/s/1i3KNsOX

**Comment by patchor** [comment]
现在下载，短时间还没有出现焦点丢失的情况。我再继续看看一下




patchor@163.com

发件人： chenall
发送时间： 2015-02-14 08:17
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] 参数窗口偶尔还是有丢失焦点的情况，尤其在输入比较快的情况下。有没有办法彻底解决呢？ (#24)
先试试之个,看看能不能解决.
http://pan.baidu.com/s/1i3KNsOX

**Comment by patchor** [comment]
![image](https://cloud.githubusercontent.com/assets/8335832/6197963/519cb81c-b42a-11e4-82e3-3bd4bf332be7.png)

**Comment by patchor** [comment]
今天发现一种情况：
如果命令输入之后，如果失去参数焦点。直接重新调用命令，还可以创建一个新的参数窗口....

这样循环，windows 就会有了多个参数输入窗口（就像上面）。不知道这个是否跟参数窗口焦点有关呢？

**Comment by chenall** [comment]
再试试这个,应该不会有这个问题,只是需要显示主界面.不太美观,先看看效果.

http://pan.baidu.com/s/1ntGB0jJ

**Comment by patchor** [comment]
下载测试了一下，这个版本好像比较稳定

但是因为现在主窗口和参数窗口并存，所以具体还需要进一步测试

**Comment by patchor** [comment]
从昨天试用到现在，一直没有发现丢失焦点的情况，我继续测试使用看看。

和丢失焦点的感觉相比之下，主窗口和参数选择窗口共同显示还是可以接受的

**Comment by patchor** [comment]
焦点保持效果很好，用起来感觉很爽！

**Comment by patchor** [comment]
最近使用结果，焦点就是次数已经非常少见！使用体验非常好

结帖子了
