### ISSUE TITLE
chenall ，在快捷命令编辑中能否帮助增加参数框和另存按钮呢？

### ISSUE THREAD

**Issue by patchor** [chenall/ALMRun#26]
![image](https://cloud.githubusercontent.com/assets/8335832/6496945/4e755ab0-c314-11e4-9671-0282cc999a2b.png)

**Comment by chenall** [comment]
把需要的参数放在命令中不是一样的吗?目前我们其实没有区分参数和命令,在运行的时候才提取的(以后会考虑分开)

**Comment by patchor** [comment]
呵呵，只是觉得分开可以更直观一点

另外，chenall 能否帮忙增加一个另存按钮呢？ 另存的试用频率，其实挺大的

**Comment by patchor** [comment]
Chenall，能否在下个版本中。在快捷键维护界面帮忙增加一个另存按钮呢？

经常需要增加类似的快捷命令比较繁琐

**Comment by chenall** [comment]
嗯,这个我会抽空处理下.

**Comment by patchor** [comment]
谢谢帮助




patchor@163.com

发件人： chenall
发送时间： 2015-03-12 14:11
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] chenall ，在快捷命令编辑中能否帮助增加参数框和另存按钮呢？ (#26)
嗯,这个我会抽空处理下.

**Comment by patchor** [comment]
最近可有新版本发布呢？ chenall

**Comment by chenall** [comment]
http://pan.baidu.com/s/1jGGH4EE#path=%252FALMRun

新的版本已经上传,实现了复制的功能.
有两种方式

1. 在命令管理器中右键菜单的复制功能.
2. 在编辑命令要保存的时候按住Ctrl键再点确定保存.

**Comment by patchor** [comment]
谢谢，新增在命令管理器中右键菜单的复制功能很完美！
