### ISSUE TITLE
chenall，能否帮忙在弹出参数窗口时重定位一下参数窗口位置呢？

### ISSUE THREAD

**Issue by patchor** [chenall/ALMRun#27]
chenall，现在在办公室里又找了一个外接显示器。这样在不同显示器上切换的时候，参数窗口会存在变化的情况。比如在笔记本上的正常显示

![image](https://cloud.githubusercontent.com/assets/8335832/6703417/94975a4a-cd76-11e4-9aec-2f9f98f6678a.png)

**Comment by patchor** [comment]
在外接显示器上由于分辨率不同，参数窗口会重定位。这时就变成了这样
![image](https://cloud.githubusercontent.com/assets/8335832/6703452/eec27bf8-cd76-11e4-987e-908fc9026bf1.png)

能否调整一下，在每次弹出参数窗口的时候将参数窗口和主窗口重点自动对其呢？ 这样可能会美观一点

**Comment by chenall** [comment]
这个我再抽空看一下.

**Comment by chenall** [comment]
http://pan.baidu.com/s/1jGGH4EE#path=%252FALMRun

新的版本已经上传不过只允许手工修改没有图形修改方法.
ALMRUN.ini中设置以下值即可
 [Window]
 DlgParamCenter=0

**Comment by patchor** [comment]
已经在ALMRUN.INI 中增加了参数行，但是好像不是很有效

![image](https://cloud.githubusercontent.com/assets/8335832/6888487/dfe2c5d6-d6b1-11e4-9f1d-784683abb72d.png)

**Comment by chenall** [comment]
退出ALMrun再修改否则可能会没有修改成功(因为缓存的关系可能会自动恢复)

**Comment by patchor** [comment]
我刚才测试了一下，感觉这个参数应是在almrun 启动时候生效的，我的使用场景可能稍微有所不同

我的场景：
上班时候会接入外接显示器，这时候如果显示是正确的
![image](https://cloud.githubusercontent.com/assets/8335832/6889282/ba0925c6-d6c5-11e4-9d7c-b8521d30bbcb.png)

**Comment by patchor** [comment]
下班时候，我会移除外接显示器、同时电脑睡眠。到家里再直接解除睡眠使用电脑，这时直接用笔记本显示器的效果为

**Comment by patchor** [comment]
![image](https://cloud.githubusercontent.com/assets/8335832/6889342/d8d273ee-d6c6-11e4-8eb2-c63c25e41913.png)

**Comment by patchor** [comment]
考虑了一下，可能这个参数的定位效果。在每次调用显示参数窗口时候都检查一次会更理想一点

**Comment by chenall** [comment]
测试该参数有无效果的方法比较简单,直接移动ALMRUN主窗口位置到左上角,然后再启动需要输入参数的程序,如果这个参数框在主窗口上就有效果了,

默认情况下这个参数窗口是自动在显示器居中的.

**Comment by patchor** [comment]
测试了一下，该参数应该是有效的。 现在有个小不便就是
 DlgParamCenter=0 仅对参数窗口有效，对ALMRUN主窗口无效，这样在切换显示器的时候，almrun 主窗口和参数窗口就错位了，能否让该参数也对almrun 生效呢？那样就舒服了

**Comment by chenall** [comment]
默认情况下ALMRun主窗口是自动居中的,你切换显示器它还是会居中
而DlgParamCenter=0 时参数窗口会自动跟随主窗口也不会发生错位的呀.

正常情况下只要隐藏再显示ALMRUN主窗口它会自动居中的,若是没有居中那应该是有BUG

**Comment by patchor** [comment]
有没有可能跟程序自动记录上次主窗口关闭时候位置相关呢？




patchor@163.com

发件人： chenall
发送时间： 2015-04-06 14:09
收件人： chenall/ALMRun
抄送： patchor
主题： Re: [ALMRun] chenall，能否帮忙在弹出参数窗口时重定位一下参数窗口位置呢？ (#27)
默认情况下ALMRun主窗口是自动居中的,你切换显示器它还是会居中
而DlgParamCenter=0 时参数窗口会自动跟随主窗口也不会发生错位的呀.
正常情况下只要隐藏再显示ALMRUN主窗口它会自动居中的,若是没有居中那应该是有BUG
