### ISSUE TITLE
请问Everything搜索是否可以直接打开文件？

### ISSUE THREAD

**Issue by youthcould** [chenall/ALMRun#28]
Almrun非常棒，谢谢你的project
目前不管是目录还是文件，打开都是直接是其所在的文件夹，请教可不可以
1. 文件的话直接打开那个文件，目前这种还要到资源管理器中中转下，略麻烦
2. 也许可以设置快捷键，比如按住shift打开指定项是打开路径，否则直接打开文件

多谢

**Comment by chenall** [comment]
正常文件是直接打开的呀

**Comment by patchor** [comment]
如果是文件，回车应该是直接打开运行。ctrl+d 会自动转到文件所在目录

**Comment by youthcould** [comment]
不好意思，是我没说清楚，在everything上确实是如两位所说
我的意思是在Almrun里面的输入框中搜索的时候（everything运行在后台），选中找到结果，然后按enter结果是打开了文件所在的目录，而不是直接打开文件

**Comment by chenall** [comment]
ALMRUN里面的文件肯定是直接打开运行的,

抱歉我还是没有明白你所说的问题.

**Comment by youthcould** [comment]
Almrun可以结合Everything，即Everything在后台时直接在Almrun的搜索框就可以直接搜索全盘文件对吧，如下图
![default](https://cloud.githubusercontent.com/assets/2182992/6806644/3b4b0852-d207-11e4-9ff1-e527717af5d1.png)

我说的问题是来利用这个功能搜索出来的文件直接在选中条目上按Enter，调用的是资源管理器打开了该文件所在目录，而不是直接运行该文件

希望可以直接运行该文件

**Comment by chenall** [comment]
OK,明白了,因为这个功能不是我增加的,我看了下这个修改比较简单,你可以自己先改一下,下个版本我会修改成默认运行文件.

修改方法在以下文件中.
ALMRun\config\sample\plugins.lua
查找
```lua
table.insert(t_command,{name=pre..v["NAME"],desc=v["PATH"],order=1090,cmd = 'Explorer /select, "'..v["FULL_PATH"]..'"'})
```
把后面的`cmd=`替换为`v["FULL_PATH"]`,也就是删除掉Explorer等字符,最终如下.
```lua
table.insert(t_command,{name=pre..v["NAME"],desc=v["PATH"],order=1090,cmd = v["FULL_PATH"]})
```

**Comment by youthcould** [comment]
OK，多谢了
Almrun真的很棒，多谢

**Comment by chenall** [comment]
同样感谢你们,有你们的使用和建议才能使得这个软件更加完善,

ps: 如果该问题已解解决请关闭issue
