### ISSUE TITLE
请问能否增加个选项：启动默认英文输入法

### ISSUE THREAD

**Issue by youthcould** [chenall/ALMRun#29]
RT.
希望可以默认启动时就是英文输入法

**Comment by chenall** [comment]
默认就是自动切换英文输入法的,除非你的系统没有添加英文键盘输入法.

**Comment by youthcould** [comment]
明白，希望的是每次按alt+r出来框框的时候都是默认英文输入法，不用记住上次是用了中文还是英文

**Comment by chenall** [comment]
正常情况下打开ALMRun时都是在英文输入法状态(可能不是很完善),需要你的系统有添加英文输入法或英文键盘
你可以查一下你的系统中是否有安装了这些输入法
注册表以下位置
```
HKEY_CURRENT_USER\Keyboard Layout\Preload
```
有这三个的其中一之`00000409`,`00000809`,`00000804`,否则自动切换不生效就会使用默认的输入法状态.

**Comment by youthcould** [comment]
多谢你的说明，可惜我就是你说的那种，只用了一种QQ输入法纯净版，只用shift切换中英文状态，这种情况是不是就没有办法了？

**Comment by chenall** [comment]
是的这个我目前没有办法,
