### ISSUE TITLE
我想要设置ALMRun，直接展现20个相关结果，请问如何设置？

### ISSUE THREAD

**Issue by xiaopangmei** [chenall/ALMRun#54]
按一下快捷键，  ALMRun出现搜索框，我键入搜索，

比如实际结果是30个，我现在希望直接可以把前20个直接展现出来，

现在的默认状态是10个结果，虽然设置选项里有个开关“仅显示前十项”，我已经关掉了，

但是还是只现在十个结果， 比如第十一个结果需要方向键一下下的去按才能看到，太不直观。

请开发组和其他会设置的指点一二，谢谢！

**Comment by xiaopangmei** [comment]
@chenall  
希望百忙之中，指点我一下，谢谢

**Comment by chenall** [comment]
不支持哦，如果懂得修改的话可以试试自己改改看，用20个相关结果还要使用方向键的，这样子就没有效率了。
