### ISSUE TITLE
无法在lua中require加载dll

### ISSUE THREAD

**Issue by crysisfair** [chenall/ALMRun#56]
Hi chanall,

我试图在lua命令中加载含有dll的第三方库（如luasocket, lpeg），总是会弹出下面的窗口

![image](https://user-images.githubusercontent.com/9649279/38692613-ddeedef2-3eb6-11e8-878f-33a31c4a05a8.png)

我的lua命令内容是

`addCommand{ name = 'mine', key = "Alt+Q", desc = 'Test my script', cmd = function()
	local p = require"lpeg"
    end
}
`

1、若是require没有dll的库，如json.lua，不会出现这个问题。
2、luasocket和lpeg在独立的luajit中可正常使用。
3、luajit版本是2.0.4。
4、将项目自带的Lua51.lib替换为luajit 2.0.4编译出来的lib，结果一样。

**Comment by chenall** [comment]
dll文件需要放到almrun.exe同目录下才可以。
