### ISSUE TITLE
ALMRun会有蓝屏后ShortCutList.txt文件乱码的问题吗？

### ISSUE THREAD

**Issue by Liber-coder** [chenall/ALMRun#65]
在ALTRun中，有时电脑蓝屏，重新启动电脑后ShortCutList.txt文件乱码，导致alt+r 弹出的界面中一片空白。不知道在ALMRun中，蓝屏等电脑错误，会不会出现类似问题？

**Comment by chenall** [comment]
在ALMRun已经有考虑到的这种情况,主配置文件和记录的是分开的,避免主配置文件丢失的情况.

具体的可以自己使用看看..

我每天都在使用,目前碰到的问题就只有order.ini会出错,其它的还没有发现问题.
