### ISSUE TITLE
程序确实好用，再请教个小问题，有办法多个指令同时执行吗？

### ISSUE THREAD

**Issue by ima-rius** [chenall/ALMRun#67]

**Comment by chenall** [comment]
shellExecute('cmd', '', '', 'max')
shellExecute('cmd', '', '', 'max')
shellExecute('cmd', '', '', 'max')

**Comment by ima-rius** [comment]
> shellExecute('cmd', '', '', 'max')
> shellExecute('cmd', '', '', 'max')
> shellExecute('cmd', '', '', 'max')

朋友，抱歉，我没有程序基础，所以不怎么看得懂。
然后我自行尝试了以下指令，但都不能执行，所以能不能再请教下。
LUA模式：
shellExecute('cmd', '"C:\\Program Files (x86)\\SPlayer\\splayer.exe"', '', 'max')
shellExecute('cmd', '', '"C:\\Program Files (x86)\\SPlayer\\splayer.exe"', 'max')
shellExecute('cmd', "C:\\Program Files (x86)\\SPlayer\\splayer.exe", '', 'max')
shellExecute('cmd', '', "C:\\Program Files (x86)\\SPlayer\\splayer.exe", 'max')
shellExecute('cmd', '"C:\\Program Files (x86)\\SPlayer\\splayer.exe"', 'max')
shellExecute('cmd',"C:\Program Files (x86)\SPlayer\splayer.exe",'max')

**Comment by chenall** [comment]
可以看一下这里的介绍。

https://github.com/chenall/ALMRun/blob/master/doc/config_api.md#1-shellexecute

```lua
shellExecute('C:\\Program Files (x86)\\SPlayer\\splayer.exe', '', '', 'max')
shellExecute('C:\\Program Files (x86)\\SPlayer\\splayer.exe', '', '', 'max')
shellExecute('C:\\Program Files (x86)\\SPlayer\\splayer.exe', '', '', 'max')
shellExecute('C:\\Program Files (x86)\\SPlayer\\splayer.exe', '', '', 'max')
```

**Comment by ima-rius** [comment]
非常感谢，功能实现了！！！
